version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
  assignees:
  - terakoya76

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  assignees:
    - terakoya76
